version: "3.8"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./:/postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adin
    ports:
      - 54321:80
    volumes:
      - ./:/pgadmin

networks:
  default:
    name: local-network
    external: true